version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.15
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.0
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
  - dependency-name: "@octokit/types"
    versions:
    - 6.10.0
    - 6.10.1
    - 6.11.1
    - 6.11.2
    - 6.12.0
    - 6.12.1
    - 6.6.0
    - 6.7.0
    - 6.7.1
    - 6.8.2
    - 6.8.3
    - 6.8.5
    - 6.9.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
  - dependency-name: typescript
    versions:
    - 4.2.3
